version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/src/
    container_name: fhircodegen_dev
    working_dir: /src
    env_file:
      - docker.env
